
ingress:
  hosts:
    - host: adminer.k8s.com
      paths:
        - path: /
          backend:  
            serviceName: adminer
            servicePort: 8080
    - host: springboot.k8s.com
      paths: 
        - path: /games-api/
          backend:
            serviceName: springboot-app
            servicePort: 8080