app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: add-image-here
    port: 8080
    config: []
    env:
      - name: temp
        value: temp
  service:
    type: NodePort
    port: 8080

  
  ingress:
    name: ingress
    # className: nginx
    enabled: true
    annotations:
      # nginx.ingress.kubernetes.io/app-root: /
      # nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/hsts: "false"
    hosts:
      - host: host
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: games-api
            servicePort: 8080
    